USE c2230446_estate;


INSERT INTO property_type(property_type) 
    VALUE('home'), 
    ('apartament'), 
    ('garage'), 
    ('shop'), 
    ('office'), 
    ('deposit'), 
    ('barn'), 
    ('land'), 
    ('hectares');

INSERT INTO users(name, surname, email, phone, pass, role) 
    VALUE('Roman', 'Martini', 'romanmartini201@gmail.com', 543533430472, MD5('MUsi159!%)'), 'admin');

INSERT INTO users(name, surname, email, phone, pass, role) 
    VALUE('user', 'user', 'user@gmail.com', 543533000000, MD5('user'), 'suscriber');


INSERT INTO users(type, name, surname, company, email, phone, pass, role) 
    VALUE('owner', 'owner', 'owner', null, 'owner@gmail.com', 543533111111, MD5('owner'), 'author'),
    ('estate', 'estate', 'estate', 'inmobiliaria X', 'estate@gmail.com', 543533222222, MD5('estate'), 'author');

INSERT INTO property(creator, title,                        description,                           img,                                     address,            city,          region,    country,      rooms,  bathrooms,  bedrooms,   total_area, covered_area,   new,    balcony,    garage,     yard,   light_yard,     lat,    lon,    contract,   currency,  price,   expenses,   type,   status) 
    VALUE(           4,       'Casa superduper gigante',    'Gran casa con 8 dormitorios',         '1.jpg 2.jpg 3.jpg 4.jpg 5.jpg 6.jpg',   'Las heras 145',    'Villa Maria', 'Córdoba', 'Argentina',  '10',   2,          8,          200,        120,            'si',    1,          3,          'si',   1,              null,   null,   'rent',     'ARS',     90000,   null,       1,      'actived'),
         (           4,       'Casa para comprar',          'Casa de 3 dormitorios p/familia',      '1.jpg 2.jpg 3.jpg 4.jpg 5.jpg 6.jpg',  'Italia 510',       'Las Varillas','Córdoba', 'Argentina',   5,     2,          3,          120,        90,            'si',      1,          1,          'si',   1,              null,   null,   'sale',     'ARS',     900000,   null,        1,      'actived'),
         (           4,       'Garage amplio',              'Garaje para tu super auto',           '1.jpg 2.jpg 3.jpg 4.jpg 5.jpg 6.jpg',   'San Juan 1857',     'Villa Maria', 'Córdoba', 'Argentina',  null, null,     null,          40,        40,                1,   null,          1,         null,   null,           null,   null,   'rent',     'ARS',       7500,   300,        3,      'actived'),
         
         (           3,       'Depto 1 dormitorio',         'Complejo de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Jujuy 20',         'Villa Maria', 'Córdoba', 'Argentina',  '2',    1,          1,          90,         90,             'si',     0,          1,        'no',   1,              null,   null,   'rent',     'ARS',      12000,  1500,       2,      'actived'),
         (           3,       'Depto 2 dormitorio',         'Complejo de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Jujuy 20',         'Villa Maria', 'Córdoba', 'Argentina',  '3',    1,          2,          100,         100,           'si',     0,          1,        'no',   1,              null,   null,   'rent',     'ARS',      15000,  1800,       2,      'actived'),
         (           3,       'Depto 3 dormitorio',         'Complejo de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Jujuy 20',         'Villa Maria', 'Córdoba', 'Argentina',  '4',    1,          3,          120,         120,           'si',     2,          1,        'no',   1,              null,   null,   'rent',     'ARS',      16000,  2000,       2,      'actived'),
         (           3,       'Depto 4 dormitorio',         'Complejo de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Jujuy 20',         'Villa Maria', 'Córdoba', 'Argentina',  '5',    1,          4,          140,         140,           'si',     2,          1,        'no',   1,              null,   null,   'rent',     'ARS',      18000,  2300,       2,      'actived'),
         (           3,       'Depto 5 dormitorio',         'Complejo de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Jujuy 20',         'Villa Maria', 'Córdoba', 'Argentina',  '6',    1,          5,          150,         150,           'si',     2,          1,        'no',   2,              null,   null,   'rent',     'ARS',      20000,  2500,       2,      'actived'),
         (           3,       'Depto 6 dormitorio',         'Complejo de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Jujuy 20',         'Villa Maria', 'Córdoba', 'Argentina',  '7',    1,          6,          160,         160,           'si',     2,          1,        'no',   2,              null,   null,   'rent',     'ARS',      25000,  2500,       2,      'actived'),
         (           3,       'Depto 1 dormitorio',         'Edificio de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Jujuy 30',         'Villa Maria', 'Córdoba', 'Argentina',  '2',    1,          1,          90,         90,             'si',     null,       1,        'no',   0,              null,   null,   'rent',     'ARS',      12000,  1500,       2,      'actived'),
         (           3,       'Depto 2 dormitorio',         'Edificio de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Jujuy 30',         'Villa Maria', 'Córdoba', 'Argentina',  '3',    1,          2,          100,         100,           'si',     0,          1,        'no',   0,              null,   null,   'rent',     'ARS',      15000,  1800,       2,      'actived'),
         (           3,       'Depto 3 dormitorio',         'Edificio de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Jujuy 30',         'Villa Maria', 'Córdoba', 'Argentina',  '4',    1,          3,          120,         120,           'si',     2,          1,        'no',   0,              null,   null,   'rent',     'ARS',      16000,  2000,       2,      'actived'),
         (           3,       'Depto 4 dormitorio',         'Edificio de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Jujuy 30',         'Villa Maria', 'Córdoba', 'Argentina',  '5',    1,          4,          140,         140,           'si',     2,       1,           'no',   null,           null,   null,   'rent',     'ARS',      18000,  2300,    2,      'actived'),
         (           3,       'Depto 5 dormitorio',         'Edificio de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Jujuy 30',         'Villa Maria', 'Córdoba', 'Argentina',  '6',    1,          5,          150,         150,           'si',     2,       1,           'no',   null,           null,   null,   'rent',     'ARS',      20000,  2500,    2,      'actived'),
         (           3,       'Depto 6 dormitorio',         'Edificio de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Jujuy 30',         'Villa Maria', 'Córdoba', 'Argentina',  '7',    1,          6,          160,         160,           'si',     2,       1,           'no',   null,           null,   null,   'rent',     'ARS',      25000,  2500,    2,      'actived'),

         (           3,       'Depto 1 dormitorio',         'Complejo de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Mendoza 120',         'Las Varillas', 'Córdoba', 'Argentina',  '2',    1,          1,          90,         90,             'si',     0,          1,        'no',   1,              null,   null,   'rent',     'ARS',      12000,  1500,       2,      'actived'),
         (           3,       'Depto 2 dormitorio',         'Complejo de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Mendoza 120',         'Las Varillas', 'Córdoba', 'Argentina',  '3',    1,          2,          100,         100,           'si',     0,          1,        'no',   1,              null,   null,   'rent',     'ARS',      15000,  1800,       2,      'actived'),
         (           3,       'Depto 3 dormitorio',         'Complejo de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Mendoza 120',         'Las Varillas', 'Córdoba', 'Argentina',  '4',    1,          3,          120,         120,           'si',     2,          1,        'no',   1,              null,   null,   'rent',     'ARS',      16000,  2000,       2,      'actived'),
         (           3,       'Depto 4 dormitorio',         'Complejo de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Mendoza 120',         'Las Varillas', 'Córdoba', 'Argentina',  '5',    1,          4,          140,         140,           'si',     2,          1,        'no',   1,              null,   null,   'rent',     'ARS',      18000,  2300,       2,      'actived'),
         (           3,       'Depto 5 dormitorio',         'Complejo de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Mendoza 120',         'Las Varillas', 'Córdoba', 'Argentina',  '6',    1,          5,          150,         150,           'si',     2,          1,        'no',   2,              null,   null,   'rent',     'ARS',      20000,  2500,       2,      'actived'),
         (           3,       'Depto 6 dormitorio',         'Complejo de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Mendoza 120',         'Las Varillas', 'Córdoba', 'Argentina',  '7',    1,          6,          160,         160,           'si',     2,          1,        'no',   2,              null,   null,   'rent',     'ARS',      25000,  2500,       2,      'actived'),
         (           3,       'Depto 1 dormitorio',         'Edificio de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Mendoza 280',         'Las Varillas', 'Córdoba', 'Argentina',  '2',    1,          1,          90,         90,             'si',     null,       1,        'no',   0,              null,   null,   'rent',     'ARS',      12000,  1500,       2,      'actived'),
         (           3,       'Depto 2 dormitorio',         'Edificio de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Mendoza 280',         'Las Varillas', 'Córdoba', 'Argentina',  '3',    1,          2,          100,         100,           'si',     0,          1,        'no',   0,              null,   null,   'rent',     'ARS',      15000,  1800,       2,      'actived'),
         (           3,       'Depto 3 dormitorio',         'Edificio de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Mendoza 280',         'Las Varillas', 'Córdoba', 'Argentina',  '4',    1,          3,          120,         120,           'si',     2,          1,        'no',   0,              null,   null,   'rent',     'ARS',      16000,  2000,       2,      'actived'),
         (           3,       'Depto 4 dormitorio',         'Edificio de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Mendoza 280',         'Las Varillas', 'Córdoba', 'Argentina',  '5',    1,          4,          140,         140,           'si',     2,       1,           'no',   null,           null,   null,   'rent',     'ARS',      18000,  2300,    2,      'actived'),
         (           3,       'Depto 5 dormitorio',         'Edificio de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Mendoza 280',         'Las Varillas', 'Córdoba', 'Argentina',  '6',    1,          5,          150,         150,           'si',     2,       1,           'no',   null,           null,   null,   'rent',     'ARS',      20000,  2500,    2,      'actived'),
         (           3,       'Depto 6 dormitorio',         'Edificio de hermosos dedepartaments', '6.jpg 7.jpg 8.jpg 9.jpg 10.jpg',        'Mendoza 280',         'Las Varillas', 'Córdoba', 'Argentina',  '7',    1,          6,          160,         160,           'si',     2,       1,           'no',   null,           null,   null,   'rent',     'ARS',      25000,  2500,    2,      'actived'),
         
         (           4,       'Casona de de patio grande',  'Casona con ventanal y patio',         '7.jpg 8.jpg 9.jpg 10.jpg',              'San Luis 458',     'Villa Maria', 'Córdoba', 'Argentina',  '5',    2,          3,          '1',        99,             'no',   null,       null,       'si',   null,           null,   null,   'sale',     'ARS',      30000,  2900,       4,      'actived')